### ISSUE TITLE
Ability to use custom revival in JSON parse

### ISSUE THREAD

**Issue by darky** [nodefluent/node-sinek#110]
For example here: https://github.com/nodefluent/node-sinek/blob/10296469e7eca9f5e4b801e23b7e3b0ee9c9587e/lib/librdkafka/NConsumer.js#L448
need to use custom revival for custom json parsing

**Comment by krystianity** [comment]
you can simply tell sinek to not parse the values to json by passing false for the toJSON argument. ```consume(syncEvent = null, asString = true, asJSON = false, options = {}) ```

**Comment by krystianity** [comment]
this way you will be able to handle the parsing of messages yourself

**Comment by darky** [comment]
Ok, thanks :+1:
