### ISSUE TITLE
NConsumer: Support custom headers

### ISSUE THREAD

**Issue by alkiskal** [nodefluent/node-sinek#121]
NConsumer send: `async send(topicName, message, _partition = null, _key = null, _partitionKey = null, _opaqueKey = null) {`

rdkafka produce: `Producer.prototype.produce = function(topic, partition, message, key, timestamp, opaque, headers) {`

There is no way to send custom headers although the underlying implementation supports it.

**Comment by krystianity** [comment]
@alkiskal would have loved to add this for you, however the high level consumer of node-rdkafka does not support https://github.com/Blizzard/node-rdkafka/blob/master/lib/producer/high-level-producer.js#L162 opaqueKey and headers

**Comment by alkiskal** [comment]
@krystianity I believe we can re-open this, correct?

https://github.com/Blizzard/node-rdkafka/commit/ba634bb71a134b794ae0a06b481af00e577cc2a4#diff-9d3a05693e055546138344d8145b175c
