### ISSUE TITLE
AutoFlush for buffer in publisher?

### ISSUE THREAD

**Issue by holgeradam** [nodefluent/node-sinek#2]
Hi,

I really like your package, great work. It would be even more pleasant if the Publisher class had an auto-flush option when using bufferPublishMessage. That way I would not have to trace the total number of messages myself.

Any chance of adding that feature?

Cheers!

**Comment by krystianity** [comment]
Hey @holgeradam thanks for your request.
I have added your wish to [sinek@3.3.0](https://github.com/krystianity/node-sinek/commit/ebd54f829dd50d0e004813f4213d7f82ea0bc893)

You can enable auto flushing of a publisher's message buffer by applying

`const publisher = new Publisher(kafkaClient);
const maxBufferSize = 500;
publisher.setAutoFlushBuffer(maxBufferSize);
`
Per default the value will be 0, which will just ignore autoFlush functionality.

**Comment by holgeradam** [comment]
Thank you, that's awesome. 💖
