### ISSUE TITLE
Implementing Murmur2 partitioner, matching the Java client's partitioning logic

### ISSUE THREAD

**Issue by vuza** [nodefluent/node-sinek#33]
Hi,

thanks for the awesome library! The default Kafka Java client is using the Murmur2 Hash function for it's partitioning algorithm. Since our system uses different clients, for us it's important, that they use consistent partitioning functions. Unfortunately neither library, nor node-rdkafka, nor librdkafka implement's the algorithm used at the default Java client. Although there is a pull request for a Murmur2 partitioner pending at librdkafka (https://github.com/edenhill/librdkafka/pull/1468), we are going to implement our own partitioning function and maybe switch to the librdkafka implementation, once it's live and supported by node-sinek and the underlaying library node-rdkafka.
Is a pull request for node-sinek, supporting the Murmur2 partitioning function welcome if well implemented? If yes we are going to fork this library and then send a pull request, otherwise we are going to solve this problem on application level.

Thank you,
Marlon

**Comment by krystianity** [comment]
Hi @vuza, I will publish sinek 6.12.0 in a few hours/days and it will include a mode to switch both js & native clients partitioning method to murmurhash2. I will still use murmurhash3 as default to make sure we dont break existing clients.

Thank you for the request :)

**Comment by vuza** [comment]
nice

**Comment by vuza** [comment]
Will close when partitioner is implemented and deployed

**Comment by krystianity** [comment]
@vuza checkout sinek@6.12.0 and switch to murmur 2 like [this](https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/README.md#switching-producer-partition-finder-mode).

**Comment by vuza** [comment]
Thank you!

**Comment by vuza** [comment]
Is there a specific reason, why you don't use the new, internal partitioning function within the `send` function?

When using send and omitting a fixed partition, a random partition gets selected: https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/NProducer.js#L315

Only when using buffer the murmur partitioning function gets used: https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/NProducer.js#L387

Would you accept an PR, applying the murmur partitioning function within the send function as well?

**Comment by krystianity** [comment]
I have been thinking about that, when I added the murmur2 option for the partitioner.
But theoretically changing from random to murmur as default is a breaking change, that could break someones application, or cause strange behaviour e.g. producing all messages on the same partition.

We could however do this in the next major release with a breaking flag.

**Comment by vuza** [comment]
Couldn't you add it to this version to the send method as an option? From
what I can see, when using send it's not possible to use the murmur
partitioner at all? You would not have to break the default behavior.

**Comment by vuza** [comment]
I'm pretty sure I'm overlooking something, but how I understand it the methods buffer and send are inconsistent, since send takes the message as a String or buffer and buffer takes the message (here called payload) as an object, although it's only a wrapper around send, calling the murmur partitioner. However, once realizing this I can totally live with that, thank you for the implementation!

**Comment by krystianity** [comment]
Nope, you are completely right @vuza it just doesnt feel right, that send and buffer have not the same behaviour (in terms of partitioning of produced messages). Lets use the murmur partitioner for plain send in the next version as well.

**Comment by krystianity** [comment]
I will create a PR for that.

**Comment by krystianity** [comment]
https://github.com/nodefluent/node-sinek/pull/42
