### ISSUE TITLE
Murmur2 partitioner fails for 'ö', 'ä', 'ü', etc. to be consistent with Kafka's default Java client

### ISSUE THREAD

**Issue by vuza** [nodefluent/node-sinek#40]
... example: The message with the key "thingäöüÄÖÜ" with a partition count of 10 should be written to the partition 2, but gets written to the partition 4 by the current implementation. Although this is not used here, it is due to the same bug described in this issue: https://github.com/b3nj4m/murmurhash-js/pull/1

I propose to use the npm package `murmur-hash-js` instead of `murmurhash` and pass a buffer instead of a string, which leads to results, consistent with Kafka's Java implementation.

The bug described got tested with this bug (https://github.com/nodefluent/node-sinek/issues/39) and that for assuming it was already resolved.

For reference see the following, tested, implementation: https://github.com/vuza/murmur2-partitioner

**Comment by vuza** [comment]
If it is okay for you @krystianity, I can push an PR, resolving this and the following bug: https://github.com/nodefluent/node-sinek/issues/39 ... since we did intensive tests on comparing JS partitioner with the default Java partitioner: https://github.com/vuza/murmur2-partitioner/blob/master/test.js

**Comment by krystianity** [comment]
Awesome go ahead :)

**Comment by krystianity** [comment]
Please also add the [seed](https://github.com/nodefluent/node-sinek/issues/39) as well.

**Comment by vuza** [comment]
This can be closed after PR is merged: https://github.com/nodefluent/node-sinek/pull/43
