### ISSUE TITLE
Documentation implies backPressure callback accepts errors

### ISSUE THREAD

**Issue by c24w** [nodefluent/node-sinek#47]
[This](https://github.com/nodefluent/node-sinek/blame/7d55877eecac871a88f48d21c7df4cdfc74c3293/lib/connect/README.md#L29-L30) part of the connect readme shows an error being passed to `callback` (albeit `null`); however, the `callback` which is passed in the [implementation](https://github.com/nodefluent/node-sinek/blob/88b954cedec635f3b4c225f1a9dce048d0db2529/lib/connect/Consumer.js#L63-L65) doesn't handle any arguments.  Am I missing something?  Should it accept errors?

**Comment by krystianity** [comment]
Yep you are right, its dropping it for the old apis sake.

**Comment by krystianity** [comment]
Fixed in 6.15.0
