### ISSUE TITLE
SSL example?

### ISSUE THREAD

**Issue by ScottChapman** [nodefluent/node-sinek#59]
I have a kafka cluster that is configured using SSL. And what I have for properties are:

- SSL_TRUSTSTORE_LOCATION
- SSL_TRUSTSTORE_PASSWORD
- BROKER_LIST (with SSL://<...> based URLs)

I'm not entirely clear how I would setup a client to consume from that kafka cluster...

**Comment by ScottChapman** [comment]
Figured it out...

**Comment by boredland** [comment]
Can you share how you did it?

**Comment by krystianity** [comment]
@ScottChapman @boredland  there is a JS SSL as well as a Native SASL-SSL consumer and producer example in this project, just check out the folders ;) (They also include config examples..)

https://github.com/nodefluent/node-sinek/tree/master/sasl-ssl-example
https://github.com/nodefluent/node-sinek/tree/master/ssl-example
