### ISSUE TITLE
Incorrect error message

### ISSUE THREAD

**Issue by SkeLLLa** [nodefluent/node-sinek#60]
Hi.

Sinek could produce incorrect error messages while loading native rdkafka client. E.g. here https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/NProducer.js#L73 original error is swallowed and new custom error is thrown.

However as rdkafka is native module it could throw not only "Module not found" exceptions. It may also throw exceptions like: "Error relocating...  symbol not found". And this is important to preserve original error message or at least show it in debug.

**Comment by krystianity** [comment]
Hi @SkeLLLa good find, I have released @6.16.0 with additional logs for this; also the error message is appended.
