### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by maraymer** [nodefluent/node-sinek#66]
Are you open to someone contributing Typescript definitions to sinek?

**Comment by krystianity** [comment]
Hi @maraymer we are more then open for TS ;) @atd-schubert was already working on this a while ago. But feel free :)

**Comment by maraymer** [comment]
@krystianity cool.  I've got a .d.ts I'm using with a project that uses node-sinek.  I'm sure its not complete -- since I haven't gotten far into the project yet, but I can share that work.  I suppose we could just do bindings only?  If we did something more significant such as rewriting the code to use TS then that's, obviously, more work :-)

**Comment by atd-schubert** [comment]
Hey @maraymer I can commit my current definition file and we can enhance it together...

**Comment by maraymer** [comment]
:100:

**Comment by maraymer** [comment]
@krystianity I have a created a project in my company GitHub page for our type definitions.  Maybe we can compare notes? https://github.com/AnomalistDesignLLC/Type-Sinek

**Comment by krystianity** [comment]
Hey @maraymer (sorry for the late reply) I just noticed that you are using the simple JS clients, our general suggestion is to always stick to the native clients NConsumer and NProducer when possible.

Feel free to create a PR for your types :)

**Comment by maraymer** [comment]
@krystianity thanks.  I'll take that under advisement.  I'll also do a PR soon.

**Comment by krystianity** [comment]
I have added more detailed typings in sinek@6.21.0 https://github.com/nodefluent/node-sinek/blob/master/index.d.ts#L93
