### ISSUE TITLE
How does `concurrency` setting behave for partitions?

### ISSUE THREAD

**Issue by jeffijoe** [nodefluent/node-sinek#67]
Hi there!

I'm looking into processing partitions in parallel, but each message in a partition one at a time in order.

In the README, I see:

```
js
const options = {
  batchSize: 500, //grab up to 500 messages per batch round
  commitEveryNBatch: 5, //commit all offsets on every 5th batch
  concurrency: 2, //calls synFunction in parallel * 2 for messages in batch
  // ...
};

myNConsumer.consume(syncFunction, true, false, options);
```

If I have **4 partitions**, will the `concurrency: 2` setting mean that I risk processing 2 messages from the same partition in parallel?

Thanks!

**Comment by krystianity** [comment]
Hi @jeffijoe in general the Kafka broker(s) will assign certain partitions to consumers of a consumer-group. Messages are buffered (depending on your settings, if you are not in 1:1 consumer mode), the concurrency setting will determine the amount of parallel processing of this message buffer in the client, therefore setting it to more than 1 will result in a chance that you are not processing messages with in the order that they were produced.

If you are depending on the message order you should always make sure:
- that you are producing messages to partitions based on a deterministic parameter e.g. key
- that you are running in 1:n consumer mode with a small but efficient batch size e.g. 250
- that you keep the concurrency setting on 1
- and only call the the message handle callback after you processed a message

**Comment by jeffijoe** [comment]
That answers my question to the point, thank you!
