### ISSUE TITLE
Resetting offsets to reprocess all messages

### ISSUE THREAD

**Issue by jeffijoe** [nodefluent/node-sinek#69]
Is it possible to "seek" to the beginning of a topic for a particular consumer group and partition?

The use case is being able to reprocess messages from the start. 😄

**Comment by krystianity** [comment]
Hi @jeffijoe basically (if you were using the native client) you could simply call the consumer.commitMessage() function and pass a faked message (the native client simply takes the offset value of the message adds 1) to tell the leading broker that you are going for a smaller offset on the next call - however to do that you would need to get all the partitions your client (part of consumer group) is assigned too (via getMetadata) and then call the function on all your consumer instances, never tried if a client that has not been assigned to a partition can still commit to it - you might want to try that though, as this way would allow you to simply reset the offset from a single consumer instance..

However, my suggestion for this is to add versions to your consumer groups e.g. "my-group-1", then simply for every re-consume you have to change the group "my-group-2" and redeploy your service.
(Dont forget to set the offset option to: "earliest")
We do this all the time and it also helps with tracking different re-consume states in metrics and logs..

**Comment by jeffijoe** [comment]
Yeah I also arrived at a similar conclusion regarding the versioning.

Do you think you might want to add the ability to reset a partition + group offset to `sinek` though? 😄

**Comment by krystianity** [comment]
@jeffijoe if I can manage to implement it without being flakey, which is always kinda difficult in Kafka environments, I might add it to sinek as feature in the future.

**Comment by krystianity** [comment]
I have added some stuff to play around @jeffijoe if you are still interested in this :P https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/NConsumer.js#L776

**Comment by jeffijoe** [comment]
Nice, is this released on npm yet? Will def try it out!

**Comment by krystianity** [comment]
Yes, but its experimental though :D let me know..

**Comment by jeffijoe** [comment]
@krystianity sorry I never got back to you on this, we stopped our Kafka experiments pretty much around the same time. Sorry for the trouble!
