### ISSUE TITLE
please provide avascrpt example for subscribing to more then one topic.

### ISSUE THREAD

**Issue by mun24** [nodefluent/node-sinek#83]
Good to see an example for javascript client subscribing to more then one topic like it is possible in kafka-node lib.

**Comment by krystianity** [comment]
Hi there @mun24 that is quite easy and can be done in multiple ways.

```javascript
const config = {..};
const moreThanOneTopic = ["one", "two", "three"];
const {NConsumer} = require("sinek");
const consumer = new NConsumer(moreThanOneTopic, config);
await consumer.connect();
consumer.consume((message, callback) => {
switch(message.topic){ .. }
callback();
});

// You can also adjust your subscriped topics during runtime of a consumer like so
consumer.adjustSubscription(moreThanOneTopic);
```

**Comment by mun24** [comment]
It is always issue with install of node-rkafka, Better to have javascript version not NConsumer.

**Comment by krystianity** [comment]
We suggest to use the NConsumer, please head over to node-rdkafka and see how you can fix the installation, it has tons of benefits :)
