### ISSUE TITLE
Should/Would node-sinek, affect process.exit behaviour

### ISSUE THREAD

**Issue by vidhill** [nodefluent/node-sinek#89]
I am replacing `kafka-node` with `node-sinek` in a project, 

We had some fail on error logic, (- Netflix philosophy, let the pod die in an error scenario)

My calls to process.exit() do not seem to cause the node application to exit any more..

I am using NConsumer
Up until the point where I call the NConsumer constructor, I can exit the process as normal..

Thanks in advance,
D

**Comment by krystianity** [comment]
Hi @vidhill I havent had problems with exits so far, but when using the NConsumer class you will spin up node-rdkafka native threads to fetch data from Kafka brokers, these might not shutdown correctly in your case. You can circumvent that by adding a listener for your process exit or SIGTERM calls and closing your application accordingly, calling: [consumer.close()](https://github.com/nodefluent/node-sinek/blob/master/lib/librdkafka/NConsumer.js#L896)

**Comment by vidhill** [comment]
Thanks for the suggestion, 
I will try that

**Comment by vidhill** [comment]
Hi, 

I can confirm that calling `consumer.close()` within an event listener for process exit does work and the application does shut down completely.

If I get a chance I will create a PR somewhere suitable to document this.

Many thanks
